const KCI_BASE_URL = 'https://kci.id/api/krl'

const REVALIDATE_STATIONS = 86400
const REVALIDATE_FARE = 3600
const REVALIDATE_SCHEDULES = 60

const UPSTREAM_TIMEOUT_MS = 8000
const UPSTREAM_RETRY_COUNT = 1

const REVALIDATE_TRAIN_SCHEDULE = 60
const ROUTE_SEARCH_WINDOW_HOURS = 3
const MAX_TRANSIT_LEGS = 3
const ROUTE_RETRY_COUNT = 2
const GET_ROUTE_CONCURRENCY = 5

export {
  KCI_BASE_URL,
  REVALIDATE_STATIONS,
  REVALIDATE_FARE,
  REVALIDATE_SCHEDULES,
  UPSTREAM_TIMEOUT_MS,
  UPSTREAM_RETRY_COUNT,
  REVALIDATE_TRAIN_SCHEDULE,
  ROUTE_SEARCH_WINDOW_HOURS,
  MAX_TRANSIT_LEGS,
  ROUTE_RETRY_COUNT,
  GET_ROUTE_CONCURRENCY,
}
